services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING_INTERVAL=500
    command: npx next dev --webpack
    restart: always

